name: Trigger Build Pipeline

on:
  push:
    branches:
      - develop
      - release

jobs:
  trigger-build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Authenticate with PAT
    - name: Authenticate with PAT
      run: |
        echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

    # Step 2: Trigger Reusable Workflow in Pipeline Repo
    - name: Trigger Reusable Workflow
      uses: pipeline-repo/.github/workflows/identity-pipeline.yml@main
      with:
        branch: ${{ github.ref_name }}               # Pass the branch name dynamically
        app_name: "hadiya-app"                      # Static value: Name of your app
        acr_name: "demoregistry124"             # Static value: Namespace in AKS
