name: Trigger Pipeline in Pipeline Repo

on:
  push:
    branches:
      - develop        # Trigger when there's a push to the 'develop' branch
      - 'release/*'    # Trigger when there's a push to any 'release/*' branch

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger the CI/CD pipeline in the Pipeline Repo
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: Abhishek-281/Pipeline-repo  # Replace with your actual pipeline repo name
          token: ${{ secrets.GH_TOKEN }}  # Use your GitHub token for authentication
          event-type: trigger-pipeline  # Custom event name
          client-payload: |
            {
              "ref": "${GITHUB_REF}"
            }  # Pass the branch name from the Hadiya-repo
