name: Use Azure Key Vault Secrets

on:
  push:
    branches:
      - main

jobs:
  use-secrets:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 2: Fetch Secrets from Azure Key Vault
      - name: Get secrets from Azure Key Vault
        uses: azure/cli@v1
        with:
          inlineScript: |
            echo "ENCRYPTION_KEY=$(az keyvault secret show --name EncryptionKey --vault-name qwertydemoprism --query value -o tsv)" >> $GITHUB_ENV
            echo "EXTERNAL_GEOFENCING_CORP_IDS=$(az keyvault secret show --name ExtenalGeoFencingCorpIds --vault-name qwertydemoprism --query value -o tsv)" >> $GITHUB_ENV

      # Step 3: Use the Secrets
      - name: Use Secrets
        run: |
          echo "Secret 1: ${{ env.ENCRYPTION_KEY }}"
          echo "Secret 2: ${{ env.EXTERNAL_GEOFENCING_CORP_IDS }}"
