name: Replace and Verify Tokens

on:
  push:
    branches:
      - develop
      - 'release/*'

jobs:
  replace-tokens:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Environment Variable
        run: |
          if [[ $GITHUB_REF == refs/heads/release/* ]]; then
            echo "ENV=uat" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == refs/heads/develop ]]; then
            echo "ENV=dev" >> $GITHUB_ENV
          fi

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS1 }}
      - name: Fetch secrets and set variables
        uses: azure/cli@v1
        with:
          inlineScript: |
            # Set Key Vault name based on environment
            
            
            # Fetch and set all secrets from Key Vault
            secrets=$(az keyvault secret list --vault-name qwertydemoprism  --query '[].name' -o tsv)
            for secret in $secrets; do
              value=$(az keyvault secret show --name $secret --vault-name qwertydemoprism  --query 'value' -o tsv)
              echo "${secret}=${value}" >> $GITHUB_ENV
            done

      - name: Replace Tokens in appsettings.json
        uses: cschleiden/replace-tokens@v1
        with:
          files: '**/appsettings.json'
          tokenPrefix: "#{" 
          tokenSuffix: "}#"
        env:
          EncryptionKey: ${{ env.EncryptionKey }}
          ExtenalGeoFencingCorpIds: ${{ env.ExtenalGeoFencingCorpIds }}
          Jwt-Expiry: ${{ env.Jwt-Expiry }}
          prismhrclientId: ${{ env.prismhrclientId }}
          service-bus-connectionstring: ${{ env.service-bus-connectionstring }}

      - name: Verify Token Replacement
        run: |
          echo "Environment: ${{ env.ENV }}"
          echo "Displaying replaced appsettings.json content:"
          cat appsettings.json
