name: Replace and Verify Tokens

on:
  push:
    branches:
      - main

jobs:
  replace-tokens:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENTID }}","clientSecret":"${{ secrets.CLIENTSECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTIONID }}","tenantId":"${{ secrets.TENANTID }}"}'

      - name: Fetch secrets and set variables
        uses: azure/cli@v1
        with:
          inlineScript: |
            echo "ENCRYPTION_KEY=$(az keyvault secret show --name EncryptionKey --vault-name qwertydemoprism --query value -o tsv)" >> $GITHUB_ENV
            echo "EXTERNAL_GEOFENCING_CORP_IDS=$(az keyvault secret show --name ExtenalGeoFencingCorpIds --vault-name qwertydemoprism --query value -o tsv)" >> $GITHUB_ENV
            echo "JWT_EXPIRY=$(az keyvault secret show --name Jwt-Expiry --vault-name qwertydemoprism --query value -o tsv)" >> $GITHUB_ENV
            echo "PRISMHR_CLIENT_ID=$(az keyvault secret show --name prismhrclientId --vault-name qwertydemoprism --query value -o tsv)" >> $GITHUB_ENV
            echo "SERVICE_BUS_CONNECTION=$(az keyvault secret show --name service-bus-connectionstring --vault-name qwertydemoprism --query value -o tsv)" >> $GITHUB_ENV

      - name: Replace Tokens in appsettings.json
        uses: cschleiden/replace-tokens@v1
        with:
          files: '**/appsetting.json'
          tokenPrefix: "#{" 
          tokenSuffix: "}#"
        env:
          EncryptionKey: ${{ env.ENCRYPTION_KEY }}
          ExtenalGeoFencingCorpIds: ${{ env.EXTERNAL_GEOFENCING_CORP_IDS }}
          Jwt-Expiry: ${{ env.JWT_EXPIRY }}
          prismhrclientId: ${{ env.PRISMHR_CLIENT_ID }}
          service-bus-connectionstring: ${{ env.SERVICE_BUS_CONNECTION }}

      - name: Verify Token Replacement
        run: |
          echo "Displaying replaced appsettings.json content:"
          cat appsetting.json
